/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author advaithnair
 */
public class MadLibsFrame extends javax.swing.JFrame {

    /**
     * Creates new form MadLibsFrame
     */
    public MadLibsFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();
        btnOK = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        PN1 = new javax.swing.JTextField();
        A1 = new javax.swing.JTextField();
        Noun1 = new javax.swing.JTextField();
        Noun2 = new javax.swing.JTextField();
        Noun3 = new javax.swing.JTextField();
        Noun4 = new javax.swing.JTextField();
        Noun5 = new javax.swing.JTextField();
        Noun6 = new javax.swing.JTextField();
        Noun7 = new javax.swing.JTextField();
        Noun8 = new javax.swing.JTextField();
        Noun9 = new javax.swing.JTextField();
        POB1 = new javax.swing.JTextField();
        POB2 = new javax.swing.JTextField();
        PN = new javax.swing.JTextField();
        Exclamation = new javax.swing.JTextField();
        Verb = new javax.swing.JTextField();
        Adjective = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaOut = new javax.swing.JTextArea();
        btnStartOver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Plural Noun");

        Name.setActionCommand("<Not Set>");
        Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameActionPerformed(evt);
            }
        });

        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        jLabel2.setText("Last Name of Person In Room");

        jLabel3.setText("Adjective");

        jLabel4.setText("Noun");

        jLabel5.setText("Noun");

        jLabel6.setText("Part of the Body");

        jLabel7.setText("Part of the Body");

        jLabel8.setText("Plural Noun");

        jLabel9.setText("Noun");

        jLabel10.setText("Noun");

        jLabel11.setText("Exclamation");

        jLabel12.setText("Noun");

        jLabel13.setText("Noun");

        jLabel14.setText("Noun");

        jLabel15.setText("Verb");

        jLabel16.setText("Noun");

        jLabel17.setText("Adjective");

        jLabel18.setText("Noun");

        jLabel19.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel19.setText("Mad Libs by Advaith Nair");

        PN1.setActionCommand("<Not Set>");
        PN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PN1ActionPerformed(evt);
            }
        });

        A1.setActionCommand("<Not Set>");
        A1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A1ActionPerformed(evt);
            }
        });

        Noun1.setActionCommand("<Not Set>");
        Noun1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Noun1ActionPerformed(evt);
            }
        });

        Noun2.setActionCommand("<Not Set>");
        Noun2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Noun2ActionPerformed(evt);
            }
        });

        Noun3.setActionCommand("<Not Set>");
        Noun3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Noun3ActionPerformed(evt);
            }
        });

        Noun4.setActionCommand("<Not Set>");
        Noun4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Noun4ActionPerformed(evt);
            }
        });

        Noun5.setActionCommand("<Not Set>");
        Noun5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Noun5ActionPerformed(evt);
            }
        });

        Noun6.setActionCommand("<Not Set>");
        Noun6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Noun6ActionPerformed(evt);
            }
        });

        Noun7.setActionCommand("<Not Set>");
        Noun7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Noun7ActionPerformed(evt);
            }
        });

        Noun8.setActionCommand("<Not Set>");
        Noun8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Noun8ActionPerformed(evt);
            }
        });

        Noun9.setActionCommand("<Not Set>");
        Noun9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Noun9ActionPerformed(evt);
            }
        });

        POB1.setActionCommand("<Not Set>");
        POB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                POB1ActionPerformed(evt);
            }
        });

        POB2.setActionCommand("<Not Set>");
        POB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                POB2ActionPerformed(evt);
            }
        });

        PN.setActionCommand("<Not Set>");
        PN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PNActionPerformed(evt);
            }
        });

        Exclamation.setActionCommand("<Not Set>");
        Exclamation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExclamationActionPerformed(evt);
            }
        });

        Verb.setActionCommand("<Not Set>");
        Verb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerbActionPerformed(evt);
            }
        });

        Adjective.setActionCommand("<Not Set>");
        Adjective.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdjectiveActionPerformed(evt);
            }
        });

        areaOut.setColumns(20);
        areaOut.setRows(5);
        jScrollPane1.setViewportView(areaOut);

        btnStartOver.setText("Start Over");
        btnStartOver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartOverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Noun9, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Noun6, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Noun7, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Noun8, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Verb, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Adjective, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Noun1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Noun2, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Noun3, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Noun4, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Noun5, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(POB1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(POB2, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PN, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Exclamation, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PN1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(A1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnStartOver, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addGap(258, 258, 258))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(PN1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(A1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(Noun1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(Noun2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(POB1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(POB2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(PN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(Noun3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(Noun4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(Exclamation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(Noun5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(Noun6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(Noun7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(Verb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(Noun8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(Adjective, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(Noun9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOK)
                    .addComponent(btnStartOver))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameActionPerformed

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        //Set strings to the values within each text field
        String name = Name.getText();
        String pn1 = PN1.getText();
        String a1 = A1.getText();
        String n1 = Noun1.getText();
        String n2 = Noun2.getText();
        String n3 = Noun3.getText();
        String n4 = Noun4.getText();
        String n5 = Noun5.getText();
        String n6 = Noun6.getText();
        String n7 = Noun7.getText();
        String n8 = Noun8.getText();
        String n9 = Noun9.getText();
        String pob1 = POB1.getText();
        String pob2 = POB2.getText();
        String pn = PN.getText();
        String ex = Exclamation.getText();
        String v = Verb.getText();
        String a = Adjective.getText();
        
        //Checks if the Text Fields are filled in at all - if they're not, it will have a length of 0, and if it is filled, the length will be more than 0
        if (name.length() != 0 && pn.length() != 0 && a1.length() != 0 && n1.length() != 0 && n2.length() != 0 && n3.length() != 0 && n4.length() != 0 && n5.length() != 0 && n6.length() != 0 && n7.length() != 0 && n8.length() != 0 && n9.length() != 0 && pob1.length() != 0 && pob2.length() != 0 && pn.length() != 0 && pn.length() != 0 && ex.length() != 0 && v.length() != 0 && a.length() != 0) {
            //Return MadLib to Text Field
            areaOut.setText("I like to eat " + pn1 + " with the " + name + " family. I find them to be " + a1 + " because" + "\n" + "they like " + n1 + ". The other day, they used their " + n2 + " to massage" + "\n" + "their " + pob1 + " and " + pob2 + ". They like to spend their time with " + pn + " or"  + "\n" + "a " + n3 + ". When they went on vacation last winter, they travelled " + "\n" + "in a " + n4 + "which wasn’t too fun for them. " + ex + " When they arrived at " + "\n" + "Denver, they were greeted to " + n5 + ", " + n6 + ", and " + n7 + ". " + "\n" + "Because of all those free goodies, they decided to " + v + " with " + "\n" + "a " + n8 + " that they found. Most people describe them as " +  a + " because " + "\n" + "they play with a " + n9 + ". I don’t know about you, but I think " + "\n" + "they’re a weird family!");
        }
        else {
            //Return Error to Text Field
            areaOut.setText("Error! You left something blank.");
        }
    }//GEN-LAST:event_btnOKActionPerformed

    private void PN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PN1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PN1ActionPerformed

    private void A1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A1ActionPerformed

    private void Noun1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Noun1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Noun1ActionPerformed

    private void Noun2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Noun2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Noun2ActionPerformed

    private void Noun3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Noun3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Noun3ActionPerformed

    private void Noun4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Noun4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Noun4ActionPerformed

    private void Noun5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Noun5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Noun5ActionPerformed

    private void Noun6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Noun6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Noun6ActionPerformed

    private void Noun7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Noun7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Noun7ActionPerformed

    private void Noun8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Noun8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Noun8ActionPerformed

    private void Noun9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Noun9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Noun9ActionPerformed

    private void POB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_POB1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_POB1ActionPerformed

    private void POB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_POB2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_POB2ActionPerformed

    private void PNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PNActionPerformed

    private void ExclamationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExclamationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExclamationActionPerformed

    private void VerbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VerbActionPerformed

    private void AdjectiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdjectiveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdjectiveActionPerformed

    private void btnStartOverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartOverActionPerformed
        //Reset all the text fields with a blank space, which is effectively back to it's initial blank state
        Name.setText("");
        PN1.setText("");
        A1.setText("");
        Noun1.setText("");
        Noun2.setText("");
        Noun3.setText("");
        Noun4.setText("");
        Noun5.setText("");
        Noun6.setText("");
        Noun7.setText("");
        Noun8.setText("");
        Noun9.setText("");
        POB1.setText("");
        POB2.setText("");
        PN.setText("");
        Exclamation.setText("");
        Verb.setText("");
        Adjective.setText("");
        
        //Reset the Text Area (MadLib display)
        areaOut.setText("");
    }//GEN-LAST:event_btnStartOverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MadLibsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MadLibsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MadLibsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MadLibsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MadLibsFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField A1;
    private javax.swing.JTextField Adjective;
    private javax.swing.JTextField Exclamation;
    private javax.swing.JTextField Name;
    private javax.swing.JTextField Noun1;
    private javax.swing.JTextField Noun2;
    private javax.swing.JTextField Noun3;
    private javax.swing.JTextField Noun4;
    private javax.swing.JTextField Noun5;
    private javax.swing.JTextField Noun6;
    private javax.swing.JTextField Noun7;
    private javax.swing.JTextField Noun8;
    private javax.swing.JTextField Noun9;
    private javax.swing.JTextField PN;
    private javax.swing.JTextField PN1;
    private javax.swing.JTextField POB1;
    private javax.swing.JTextField POB2;
    private javax.swing.JTextField Verb;
    private javax.swing.JTextArea areaOut;
    private javax.swing.JButton btnOK;
    private javax.swing.JButton btnStartOver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
